language: cpp
sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7

compiler:
  #- clang
  - gcc-7

env: WHICHGCC=7 USE_CPP=17
  - CC=gcc-7
  - CXX=g++-7

install:
  - wget -O boost_1_64_0.tar.gz http://sourceforge.net/projects/boost/files/boost/1.64.0/boost_1_64_0.tar.gz/download
  - tar xzf boost_1_64_0.tar.gz
  - cd boost_1_64_0/
  - ./bootstrap.sh --prefix=/usr/local --with-libraries=date_time,regex,test
  - (./b2 -j2 link=shared threading=multi variant=release) > /dev/null
  - (sudo ./b2 install ) > /dev/null
  - cd ..

before_script:
  - mkdir build
  - cd build
  - cmake -D CMAKE_CXX_COMPILER=g++-7 ..

script:
  - make

after_success:
  - coveralls

notifications:
  email: false

