language: cpp
sudo: required

#before_install:
#  - sudo add-apt-repository -y ppa:boost-latest/ppa
#  - sudo apt-get update -qq

install:
  - sudo wget -O boost_1_64_0.tar.gz http://sourceforge.net/projects/boost/files/boost/1.64.0/boost_1_64_0.tar.gz/download
  - sudo tar xzvf boost_1_64_0.tar.gz
  - cd boost_1_64_0/
  - sudo ./bootstrap.sh --prefix=/usr/local --with-libraries=date_time,regex,test
  - sudo ./b2 link=shared threading=multi variant=release
  - sudo ./b2 install 
  #- sudo apt-get install libboost1.60-all-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
