language: cpp
sudo: required

before_install:
  - sudo add-apt-repository ppa:boost-latest/ppa
  - sudo apt-get update

install:
  - sudo apt-cache search libboost

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
