language: cpp
sudo: false

compiler:
  #- clang
  - gcc

before_install:
  # g++4.8.1
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  # clang 3.4
  - if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi
  - sudo apt-get update -qq
      #

install:
  - sudo apt-get install -qq g++-5

  - wget -O boost_1_64_0.tar.gz http://sourceforge.net/projects/boost/files/boost/1.64.0/boost_1_64_0.tar.gz/download
  - tar xzf boost_1_64_0.tar.gz
  - cd boost_1_64_0/
  - ./bootstrap.sh --prefix=/usr/local --with-libraries=date_time,regex,test
  - (./b2 -j2 link=shared threading=multi variant=release) > /dev/null
  - (sudo ./b2 install ) > /dev/null
  - cd ..

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make

notifications:
  email: false

after_success:
  - codecov
