language: cpp
sudo: false

#addons:
#  apt:
#    sources:
#    - ubuntu-toolchain-r-test
#    packages:
#    - g++-7

compiler:
  #- clang
  - gcc-7

env: WHICHGCC=7 USE_CPP=17
  - CC=gcc-7
  - CXX=g++-7
  - CODACY_PROJECT_TOKEN=5864916546a94520b05af1b70cdbaebd
  - COVERALLS_TOKEN=xMDW3M21AJDVeB3pVhIL6Sh28hQQ07Top

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install g++-7
  - pip install --user cpp-coveralls
  - sudo apt-get install lcov
  - gem install coveralls-lcov

install:
  # required by coverall:
  - sudo apt-get --assume-yes install lcov curl
  - wget -O boost_1_64_0.tar.gz http://sourceforge.net/projects/boost/files/boost/1.64.0/boost_1_64_0.tar.gz/download
  - tar xzf boost_1_64_0.tar.gz
  - cd boost_1_64_0/
  - ./bootstrap.sh --prefix=/usr/local --with-libraries=date_time,regex,test
  - (./b2 -j2 link=shared threading=multi variant=release) > /dev/null
  - (sudo ./b2 install ) > /dev/null
  - cd ..

before_script:
  - mkdir build
  - cd build
  - lcov --directory . --zerocounters
  - cmake -DCMAKE_CXX_COMPILER=g++-7 -DCOVERAGE=1 ..

script:
  - make -j2
  - ctest

after_success:
  - lcov --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info 'tests/*' '/usr/*' --output-file coverage.info
  - lcov --list coverage.info
  - coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info
  #- coveralls --root . --gcov-options '\-lp'

notifications:
  email: false

