language: cpp
sudo: false

#addons:
#  apt:
#    sources:
#    - ubuntu-toolchain-r-test
#    packages:
#    - g++-7

compiler:
  #- clang
  - gcc-7

env: WHICHGCC=7 USE_CPP=17
  - CC=gcc-7
  - CXX=g++-7
  - CODACY_PROJECT_TOKEN=5864916546a94520b05af1b70cdbaebd

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install gcc-7 g++-7
  - pip install --user cpp-coveralls

install:
  # required by coverall:
  - sudo apt-get --assume-yes install lcov curl
  - wget -O boost_1_64_0.tar.gz http://sourceforge.net/projects/boost/files/boost/1.64.0/boost_1_64_0.tar.gz/download
  - tar xzf boost_1_64_0.tar.gz
  - cd boost_1_64_0/
  - ./bootstrap.sh --prefix=/usr/local --with-libraries=date_time,regex,test
  - (./b2 -j2 link=shared threading=multi variant=release) > /dev/null
  - (sudo ./b2 install ) > /dev/null
  - cd ..

before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=g++-7 -DCOVERAGE=1 -DCOVERALLS=ON -DCOVERALLS_UPLOAD=ON -DENABLE_TESTING=ON ..

script:
  - make
  - ctest

after_success:
  - coveralls --root . --gcov-options '\-lp'

notifications:
  email: false

