language: cpp
before_script:
  - sudo apt-cache search libboost
  - sudo add-apt-repository ppa:apokluda/boost1.62 --yes
  - sudo apt-get update
  - mkdir build
  - cd build
  - cmake ..
script:
  - make
